spring:
  application:
    name: service-discovery-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

service.discovery.client.secret: kek444jjj